In [1]:
import  numpy as np

In [3]:
# Sort,search & counting Functions

In [4]:
arr = np.array([4,3,6,72,3,5,1,2,3,5])

In [5]:
np.sort(arr)

array([ 1,  2,  3,  3,  3,  4,  5,  5,  6, 72])

In [6]:
np.searchsorted(arr,34)

10

In [7]:
arr1 = np.array([0,34,5,2,5,2,36,1,2,3,5])

In [8]:
np.count_nonzero(arr1)

10

In [9]:
np.where(arr>6)

(array([3]),)

In [10]:
np.extract(arr>6,arr)

array([72])

In [11]:
# Numpy Byte Swapping

In [12]:
arr.byteswap()

array([ 288230376151711744,  216172782113783808,  432345564227567616,
       5188146770730811392,  216172782113783808,  360287970189639680,
         72057594037927936,  144115188075855872,  216172782113783808,
        360287970189639680])

In [13]:
# Numpy Copies & views

In [14]:
arr

array([ 4,  3,  6, 72,  3,  5,  1,  2,  3,  5])

In [15]:
a = np.copy(arr)

In [16]:
a

array([ 4,  3,  6, 72,  3,  5,  1,  2,  3,  5])

In [17]:
b = arr.view()

In [18]:
b

array([ 4,  3,  6, 72,  3,  5,  1,  2,  3,  5])

In [19]:
# Numpy - Matrix Library

In [20]:
import numpy.matlib as nm

In [21]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [22]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [24]:
# Numpy Linear Algebra

In [25]:
arr1 = np.random.randint([[2,3],[4,5]])

In [26]:
arr2 = np.random.randint([[5,3],[2,5]])

In [27]:
np.dot(arr1,arr2)

array([[ 4,  5],
       [12,  3]])