In [2]:
import numpy as np

In [3]:
# Numpy array manipulation

In [4]:
arr = np.random.randint(1,10,(3,4))

In [5]:
arr

array([[2, 6, 6, 3],
       [6, 5, 1, 3],
       [5, 6, 4, 6]])

In [6]:
arr.reshape(6,2)

array([[2, 6],
       [6, 3],
       [6, 5],
       [1, 3],
       [5, 6],
       [4, 6]])

In [7]:
arr.reshape(2,-6458484)

array([[2, 6, 6, 3, 6, 5],
       [1, 3, 5, 6, 4, 6]])

In [8]:
arr.T

array([[2, 6, 5],
       [6, 5, 6],
       [6, 1, 4],
       [3, 3, 6]])

In [9]:
arr.flatten()

array([2, 6, 6, 3, 6, 5, 1, 3, 5, 6, 4, 6])

In [10]:
arr1 = np.array([1,2,3,4])

In [11]:
arr1

array([1, 2, 3, 4])

In [12]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [14]:
arr

array([[2, 6, 6, 3],
       [6, 5, 1, 3],
       [5, 6, 4, 6]])

In [15]:
np.squeeze(arr)

array([[2, 6, 6, 3],
       [6, 5, 1, 3],
       [5, 6, 4, 6]])

In [16]:
data = np.array([[1],[2],[3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
arr1

array([1, 2, 3, 4])

In [20]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [21]:
np.roll(arr1,3)

array([2, 3, 4, 1])

In [22]:
arr1

array([1, 2, 3, 4])

In [23]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
# Numpy Binary Operation

In [25]:
arr1 = np.random.randint(1,10,(3,4))

In [26]:
arr2 = np.random.randint(1,10,(3,4))

In [27]:
arr1

array([[3, 4, 4, 9],
       [4, 4, 2, 2],
       [3, 7, 1, 7]])

In [28]:
arr2

array([[1, 6, 9, 5],
       [7, 6, 9, 9],
       [5, 4, 2, 9]])

In [29]:
arr1 + arr2

array([[ 4, 10, 13, 14],
       [11, 10, 11, 11],
       [ 8, 11,  3, 16]])

In [30]:
arr1*arr2

array([[ 3, 24, 36, 45],
       [28, 24, 18, 18],
       [15, 28,  2, 63]])

In [31]:
arr1/arr2

array([[3.        , 0.66666667, 0.44444444, 1.8       ],
       [0.57142857, 0.66666667, 0.22222222, 0.22222222],
       [0.6       , 1.75      , 0.5       , 0.77777778]])

In [32]:
arr1-arr2

array([[ 2, -2, -5,  4],
       [-3, -2, -7, -7],
       [-2,  3, -1, -2]])

In [33]:
arr1%arr2

array([[0, 4, 4, 4],
       [4, 4, 2, 2],
       [3, 3, 1, 7]])

In [34]:
arr1 & arr2

array([[1, 4, 0, 1],
       [4, 4, 0, 0],
       [1, 4, 0, 1]])

In [35]:
arr1 | arr2

array([[ 3,  6, 13, 13],
       [ 7,  6, 11, 11],
       [ 7,  7,  3, 15]])

In [36]:
arr1 | arr2

array([[11,  6,  3,  5],
       [12, 14,  3,  7],
       [ 7,  3,  7, 13]])

~arr1

array([[-3, -3, -2, -5],
       [-9, -9, -3, -4],
       [-4, -4, -5, -9]])

~arr2

array([[-10,  -7,  -3,  -6],
       [ -5,  -7,  -4,  -5],
       [ -8,  -4,  -8,  -6]])

arr1 > arr2

array([[False, False, False, False],
       [ True,  True, False, False],
       [False, False, False,  True]])

# Numpy String Function

arr = np.array(['sudh','kumar'])

np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

# Numpy Mathematical Function

np.sin(arr1)

array([[ 0.90929743,  0.90929743,  0.84147098, -0.7568025 ],
       [ 0.98935825,  0.98935825,  0.90929743,  0.14112001],
       [ 0.14112001,  0.14112001, -0.7568025 ,  0.98935825]])

np.cos(arr1)

array([[-0.41614684, -0.41614684,  0.54030231, -0.65364362],
       [-0.14550003, -0.14550003, -0.41614684, -0.9899925 ],
       [-0.9899925 , -0.9899925 , -0.65364362, -0.14550003]])

np.tan(arr1)

array([[-2.18503986, -2.18503986,  1.55740772,  1.15782128],
       [-6.79971146, -6.79971146, -2.18503986, -0.14254654],
       [-0.14254654, -0.14254654,  1.15782128, -6.79971146]])

np.tanh(arr1)



NameError: name 'array' is not defined

In [37]:
~arr2

array([[ -2,  -7, -10,  -6],
       [ -8,  -7, -10, -10],
       [ -6,  -5,  -3, -10]])

In [38]:
arr1 > arr2

array([[ True, False, False,  True],
       [False, False, False, False],
       [False,  True, False, False]])

In [39]:
# Numpy String Function

In [40]:
arr = np.array(['sudh','kumar'])

In [41]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [42]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [43]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [44]:
# Numpy Mathematical Function

In [45]:
np.sin(arr1)

array([[ 0.14112001, -0.7568025 , -0.7568025 ,  0.41211849],
       [-0.7568025 , -0.7568025 ,  0.90929743,  0.90929743],
       [ 0.14112001,  0.6569866 ,  0.84147098,  0.6569866 ]])

In [46]:
np.cos(arr1)

array([[-0.9899925 , -0.65364362, -0.65364362, -0.91113026],
       [-0.65364362, -0.65364362, -0.41614684, -0.41614684],
       [-0.9899925 ,  0.75390225,  0.54030231,  0.75390225]])

In [47]:
np.tan(arr1)

array([[-0.14254654,  1.15782128,  1.15782128, -0.45231566],
       [ 1.15782128,  1.15782128, -2.18503986, -2.18503986],
       [-0.14254654,  0.87144798,  1.55740772,  0.87144798]])

In [48]:
np.tanh(arr1)

array([[0.99505475, 0.9993293 , 0.9993293 , 0.99999997],
       [0.9993293 , 0.9993293 , 0.96402758, 0.96402758],
       [0.99505475, 0.99999834, 0.76159416, 0.99999834]])

In [49]:
np.log10(arr1)

array([[0.47712125, 0.60205999, 0.60205999, 0.95424251],
       [0.60205999, 0.60205999, 0.30103   , 0.30103   ],
       [0.47712125, 0.84509804, 0.        , 0.84509804]])

In [50]:
np.exp(arr1)

array([[2.00855369e+01, 5.45981500e+01, 5.45981500e+01, 8.10308393e+03],
       [5.45981500e+01, 5.45981500e+01, 7.38905610e+00, 7.38905610e+00],
       [2.00855369e+01, 1.09663316e+03, 2.71828183e+00, 1.09663316e+03]])

In [51]:
np.sqrt(arr1)

array([[1.73205081, 2.        , 2.        , 3.        ],
       [2.        , 2.        , 1.41421356, 1.41421356],
       [1.73205081, 2.64575131, 1.        , 2.64575131]])

In [52]:
np.power(arr1,2)

array([[ 9, 16, 16, 81],
       [16, 16,  4,  4],
       [ 9, 49,  1, 49]])

In [53]:
np.mean(arr1)

4.166666666666667

In [54]:
np.median(arr1)

4.0

In [55]:
np.std(arr1)

2.266911751455907

In [56]:
np.min(arr1)

1

In [57]:
np.max(arr1)

9

In [58]:
np.concatenate(arr1,arr2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [59]:
np.power(arr1,2)

array([[ 9, 16, 16, 81],
       [16, 16,  4,  4],
       [ 9, 49,  1, 49]])

In [60]:
np.flip(arr1)

array([[7, 1, 7, 3],
       [2, 2, 4, 4],
       [9, 4, 4, 3]])

In [61]:
arr1

array([[3, 4, 4, 9],
       [4, 4, 2, 2],
       [3, 7, 1, 7]])