In [5]:
import numpy as np

In [6]:
l = [1,2,3,4]

In [10]:
ar = np.array(l)

In [11]:
ar

array([1, 2, 3, 4])

In [12]:
type(ar)

numpy.ndarray

In [13]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [14]:
np.asarray(l)

array([1, 2, 3, 4])

In [20]:
a = [[2,3,4],[6,5,4]]

In [21]:
np.asanyarray(a)

array([[2, 3, 4],
       [6, 5, 4]])

In [24]:
b = np.matrix(a)

In [25]:
b

matrix([[2, 3, 4],
        [6, 5, 4]])

In [26]:
a = np.array(l)

In [34]:
a

array([100,   2,   3,   4])

In [28]:
c = a

In [29]:
c

array([1, 2, 3, 4])

In [31]:
c[0] = 100

In [32]:
c

array([100,   2,   3,   4])

In [33]:
a

array([100,   2,   3,   4])

In [35]:
d = np.copy(a)

In [36]:
d

array([100,   2,   3,   4])

In [38]:
a[0] = 400

In [39]:
a

array([400,   2,   3,   4])

In [40]:
d

array([100,   2,   3,   4])

In [41]:
np.fromfunction(lambda i,j : i == j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [42]:
np.fromfunction(lambda i,j : i * j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [247]:
iterable = (i*i for i in range(5))

In [248]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [50]:
np.fromstring('124 65', sep=' ')

array([124.,  65.])

In [51]:
# Numpy Data Types

In [52]:
l = [1,2,3,4,5,6]

In [53]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [54]:
ar

array([1, 2, 3, 4])

In [55]:
ar.ndim

1

In [56]:
ar2 = np.array([[1,2],[3,4]])

In [57]:
ar2.ndim

2

In [58]:
ar.size

4

In [60]:
ar2.shape

(2, 2)

In [61]:
ar.dtype

dtype('int64')

In [63]:
ar22 = np.array([(1,2,3,5.0),(4.0,1,23,5)])

In [64]:
ar22

array([[ 1.,  2.,  3.,  5.],
       [ 4.,  1., 23.,  5.]])

In [65]:
list(range(5))

[0, 1, 2, 3, 4]

In [68]:
list(range(5))

[0, 1, 2, 3, 4]

In [71]:
list(np.arange(1/4,5))

[0.25, 1.25, 2.25, 3.25, 4.25]

In [77]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [78]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [79]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [97]:
d = np.zeros((3,4,3,5,4,4,5,8,4,6,5,2,4))

In [98]:
d.ndim

13

In [103]:
o = np.ones((3,4))

In [104]:
o + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [109]:
np.empty((3,5))

array([[6.9360869e-310, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        6.3240403e-322]])

In [110]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [186]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [187]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [188]:
arr = np.random.randn(3,4)

In [189]:
import pandas as pd

pd.DataFrame(arr)

0         1         2         3
0  1.902487  1.123803 -0.661441  0.878213
1  0.253485  0.536352  1.000446  1.070922
2 -0.402085  1.004493  0.596554  0.583034

In [190]:
np.random.rand(3,4)

array([[0.63041204, 0.61095247, 0.15642793, 0.83431129],
       [0.97890454, 0.42135081, 0.95438996, 0.31787071],
       [0.22685241, 0.39410854, 0.98599342, 0.92131846]])

In [191]:
pd.DataFrame(np.random.randint(1,110,(3500,4000))).to_csv('test.csv')

In [192]:
arr = np.random.rand(3,4)

In [193]:
arr

array([[0.35056827, 0.7061065 , 0.78426806, 0.63252407],
       [0.56775942, 0.3517862 , 0.64881198, 0.89323005],
       [0.6493298 , 0.42971822, 0.95149955, 0.78472603]])

In [194]:
aar1  = arr.reshape(6,-1)

In [195]:
aar1[0][1]

0.7061064962515968

In [196]:
aar1

array([[0.35056827, 0.7061065 ],
       [0.78426806, 0.63252407],
       [0.56775942, 0.3517862 ],
       [0.64881198, 0.89323005],
       [0.6493298 , 0.42971822],
       [0.95149955, 0.78472603]])

In [197]:
aar1[1:4,1]

array([0.63252407, 0.3517862 , 0.89323005])

In [198]:
aar1 > 2

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [199]:
arr1 = np.random.randint(1,110,(5,3))

In [200]:
arr1

array([[41, 79, 92],
       [21, 23, 31],
       [18, 68, 95],
       [32,  9, 66],
       [51, 51, 54]])

In [201]:
arr1 > 50

array([[False,  True,  True],
       [False, False, False],
       [False,  True,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [202]:
arr1[2:4,(1,2)]

array([[68, 95],
       [ 9, 66]])

In [203]:
arr1[0][0] = 5000

In [204]:
arr1

array([[5000,   79,   92],
       [  21,   23,   31],
       [  18,   68,   95],
       [  32,    9,   66],
       [  51,   51,   54]])

In [205]:
# numpy functions

In [206]:
arr1 = np.random.randint(1,3,(3,3))

In [207]:
arr1

array([[2, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [208]:
arr2 = np.random.randint(1,3,(3,3))

In [209]:
arr2

array([[2, 2, 2],
       [1, 2, 1],
       [1, 2, 1]])

In [210]:
arr1 + arr2

array([[4, 4, 3],
       [2, 4, 2],
       [2, 4, 2]])

In [211]:
arr1 - arr2

array([[ 0,  0, -1],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [212]:
arr1@arr2

array([[ 7, 10,  7],
       [ 5,  8,  5],
       [ 5,  8,  5]])

In [213]:
arr1/0

/tmp/ipykernel_19476/1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [214]:
arr1 + 100

array([[102, 102, 101],
       [101, 102, 101],
       [101, 102, 101]])

In [216]:
arr1 ** 2

array([[4, 4, 1],
       [1, 4, 1],
       [1, 4, 1]])

In [217]:
# Numpy Broadcasting

In [221]:
arr =np.zeros((4,4))

In [233]:
row  = np.array([[1,2,3,4],])

In [234]:
row

array([[1, 2, 3, 4]])

In [236]:
arr + row.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [238]:
arr1 = np.random.randint(1,4,(3,4))

In [239]:
arr1

array([[3, 2, 1, 3],
       [2, 3, 1, 3],
       [2, 2, 2, 3]])

In [241]:
np.sqrt(arr1)

array([[1.73205081, 1.41421356, 1.        , 1.73205081],
       [1.41421356, 1.73205081, 1.        , 1.73205081],
       [1.41421356, 1.41421356, 1.41421356, 1.73205081]])

In [242]:
np.log(arr1)

array([[1.09861229, 0.69314718, 0.        , 1.09861229],
       [0.69314718, 1.09861229, 0.        , 1.09861229],
       [0.69314718, 0.69314718, 0.69314718, 1.09861229]])

In [243]:
np.exp(arr1)

array([[20.08553692,  7.3890561 ,  2.71828183, 20.08553692],
       [ 7.3890561 , 20.08553692,  2.71828183, 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 , 20.08553692]])

In [245]:
np.log2(arr1)

array([[1.5849625, 1.       , 0.       , 1.5849625],
       [1.       , 1.5849625, 0.       , 1.5849625],
       [1.       , 1.       , 1.       , 1.5849625]])